# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G6WvPyOo-5Wi5kJqX0JddffBJr-hLE-8
"""

!pip install streamlit pyngrok tensorflow opencv-python Pillow

from google.colab import files
uploaded = files.upload()

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import numpy as np
# import tensorflow as tf
# from PIL import Image
# import cv2
# 
# # Load model
# model = tf.keras.models.load_model("cassava_model.h5")
# 
# # IMPORTANT: match class order
# class_names = [
#     "Bacterial Blight",
#     "Brown Streak Disease",
#     "Green Mottle",
#     "Healthy",
#     "Mosaic Disease"
# ]
# 
# treatment = {
#     "Bacterial Blight": "Avoid overhead watering, use clean stems.",
#     "Brown Streak Disease": "Remove infected plants.",
#     "Green Mottle": "Use virus-free cuttings.",
#     "Healthy": "Plant is healthy.",
#     "Mosaic Disease": "Control whiteflies."
# }
# 
# st.title("🌿 Cassava Disease Detector")
# 
# file = st.file_uploader("Upload Leaf Image")
# 
# if file:
#     image = Image.open(file)
#     st.image(image)
# 
#     img = np.array(image)
#     img = cv2.resize(img, (224,224))
#     img = img / 255.0
#     img = np.reshape(img, (1,224,224,3))
# 
#     if st.button("Predict"):
#         pred = model.predict(img)
#         idx = np.argmax(pred)
#         confidence = np.max(pred)*100
# 
#         disease = class_names[idx]
# 
#         st.success(f"Prediction: {disease}")
#         st.write(f"Confidence: {confidence:.2f}%")
#         st.info(f"Treatment: {treatment[disease]}")

!pip install streamlit pyngrok

!ngrok config add-authtoken 3D1Td4yaJdO045a3mhQlVSgcw6z_5VAZ2CztPzFmGV5WYPHs

from pyngrok import ngrok

url = ngrok.connect(8501)
print("OPEN THIS LINK:", url)

!streamlit run app.py &