# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F-wKk6iafvpi5kUM_yNlgts6CCu45J3E
"""

# Install required libraries
!pip install tensorflow opencv-python matplotlib

from google.colab import drive
drive.mount('/content/drive')

import os

os.listdir('/content/drive/MyDrive')

!unzip "/content/drive/MyDrive/cassava_leaf_disease_classification.zip" -d /content/

import os
os.listdir('/content/data')

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import matplotlib.pyplot as plt
import numpy as np

train_dir = "/content/data"

from tensorflow.keras.preprocessing.image import ImageDataGenerator

IMG_SIZE = 224
BATCH_SIZE = 32

datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2
)

train_data = datagen.flow_from_directory(
    train_dir,
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    subset='training'
)

val_data = datagen.flow_from_directory(
    train_dir,
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    subset='validation'
)

print(train_data.class_indices)

class_names = [
    "Bacterial Blight",
    "Brown Streak Disease",
    "Green Mottle",
    "Healthy",
    "Mosaic Disease"
]

import tensorflow as tf

# MobileNetV2 base model
base_model = tf.keras.applications.MobileNetV2(
    input_shape=(224, 224, 3),
    include_top=False,
    weights='imagenet'
)

base_model.trainable = False

# Full model
model = tf.keras.Sequential([
    base_model,
    tf.keras.layers.GlobalAveragePooling2D(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(train_data.num_classes, activation='softmax')
])

# Compile
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

# Train
history = model.fit(
    train_data,
    validation_data=val_data,
    epochs=5
)

model.fit(train_data, validation_data=val_data, epochs=5)

model.save("cassava_model.h5")

from google.colab import files
files.download("cassava_model.h5")

print(train_data.class_indices)